# Generated by Django 2.2.4 on 2019-08-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='albums',
            field=models.ManyToManyField(through='chinook.Track', to='chinook.Album'),
        ),
    ]
