# Generated by Django 2.2.4 on 2019-08-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0002_genre_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatype',
            name='albums',
            field=models.ManyToManyField(through='chinook.Track', to='chinook.Album'),
        ),
    ]
